use_frameworks!

target 'ScryfallApiSwift_Example' do
  pod 'ScryfallApiSwift', :path => '../'

  target 'ScryfallApiSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
