# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do

#Running tests
  desc "Compiles the example code and runs the tests"
  lane :run_tests do
​    scan
  end

#

end