# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do

#Running tests on iPhone 8, and cleaning project folder before execution
  desc "Compiles the example code and runs the tests"
  lane :tests do
	scan(workspace: "Example/ScryfallApiSwift.xcworkspace",
	     clean: true, 
	     device: 'iPhone 8')
	end

#Performs Pod lib lint
  desc "Performs a pod lib lint ScryfallApiSwift.podspec"
  lane :run_pod do
	pod_lib_lint(verbose: true)
    end

end